#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v4
# autospec commit: 3d985eb
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : polkit-qt6
Version  : 1.0.114.0
Release  : 9
URL      : https://download.kde.org/stable/polkit-qt-1/polkit-qt-1-0.114.0.tar.xz
Source0  : https://download.kde.org/stable/polkit-qt-1/polkit-qt-1-0.114.0.tar.xz
Source1  : https://download.kde.org/stable/polkit-qt-1/polkit-qt-1-0.114.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 LGPL-2.0
Requires: polkit-qt6-lib = %{version}-%{release}
Requires: polkit-qt6-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : buildreq-qt6
BuildRequires : extra-cmake-modules
BuildRequires : pkg-config
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(polkit-agent-1)
BuildRequires : pkgconfig(polkit-gobject-1)
BuildRequires : qtbase-dev
BuildRequires : qtbase-dev mesa-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Polkit-qt
========
What is Polkit-qt?
------------------
Polkit-qt is a library that lets developers use the PolicyKit API through a nice
Qt-styled API. It is mainly a wrapper around QAction and QAbstractButton that
lets you integrate those two component easily with PolicyKit

%package dev
Summary: dev components for the polkit-qt6 package.
Group: Development
Requires: polkit-qt6-lib = %{version}-%{release}
Provides: polkit-qt6-devel = %{version}-%{release}
Requires: polkit-qt6 = %{version}-%{release}

%description dev
dev components for the polkit-qt6 package.


%package lib
Summary: lib components for the polkit-qt6 package.
Group: Libraries
Requires: polkit-qt6-license = %{version}-%{release}

%description lib
lib components for the polkit-qt6 package.


%package license
Summary: license components for the polkit-qt6 package.
Group: Default

%description license
license components for the polkit-qt6 package.


%prep
%setup -q -n polkit-qt-1-0.114.0
cd %{_builddir}/polkit-qt-1-0.114.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1710337851
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DQT_MAJOR_VERSION=6
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DQT_MAJOR_VERSION=6
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1710337851
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/polkit-qt6
cp %{_builddir}/polkit-qt-1-0.114.0/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/polkit-qt6/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c || :
cp %{_builddir}/polkit-qt-1-0.114.0/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/polkit-qt6/3e8971c6c5f16674958913a94a36b1ea7a00ac46 || :
cp %{_builddir}/polkit-qt-1-0.114.0/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/polkit-qt6/a4c60b3fefda228cd7439d3565df043192fef137 || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/polkit-qt5-1/PolkitQt1/ActionDescription
/usr/include/polkit-qt5-1/PolkitQt1/Agent/Listener
/usr/include/polkit-qt5-1/PolkitQt1/Agent/Session
/usr/include/polkit-qt5-1/PolkitQt1/Authority
/usr/include/polkit-qt5-1/PolkitQt1/Details
/usr/include/polkit-qt5-1/PolkitQt1/Gui/Action
/usr/include/polkit-qt5-1/PolkitQt1/Gui/ActionButton
/usr/include/polkit-qt5-1/PolkitQt1/Gui/ActionButtons
/usr/include/polkit-qt5-1/PolkitQt1/Identity
/usr/include/polkit-qt5-1/PolkitQt1/Subject
/usr/include/polkit-qt5-1/PolkitQt1/TemporaryAuthorization
/usr/include/polkit-qt5-1/polkitqt1-actiondescription.h
/usr/include/polkit-qt5-1/polkitqt1-agent-export.h
/usr/include/polkit-qt5-1/polkitqt1-agent-listener.h
/usr/include/polkit-qt5-1/polkitqt1-agent-session.h
/usr/include/polkit-qt5-1/polkitqt1-authority.h
/usr/include/polkit-qt5-1/polkitqt1-core-export.h
/usr/include/polkit-qt5-1/polkitqt1-details.h
/usr/include/polkit-qt5-1/polkitqt1-gui-action.h
/usr/include/polkit-qt5-1/polkitqt1-gui-actionbutton.h
/usr/include/polkit-qt5-1/polkitqt1-gui-actionbuttons.h
/usr/include/polkit-qt5-1/polkitqt1-gui-export.h
/usr/include/polkit-qt5-1/polkitqt1-identity.h
/usr/include/polkit-qt5-1/polkitqt1-subject.h
/usr/include/polkit-qt5-1/polkitqt1-temporaryauthorization.h
/usr/include/polkit-qt5-1/polkitqt1-version.h
/usr/lib64/cmake/PolkitQt5-1/PolkitQt5-1Config.cmake
/usr/lib64/cmake/PolkitQt5-1/PolkitQt5-1ConfigVersion.cmake
/usr/lib64/cmake/PolkitQt5-1/PolkitQt5-1Targets-relwithdebinfo.cmake
/usr/lib64/cmake/PolkitQt5-1/PolkitQt5-1Targets.cmake
/usr/lib64/libpolkit-qt5-agent-1.so
/usr/lib64/libpolkit-qt5-core-1.so
/usr/lib64/libpolkit-qt5-gui-1.so
/usr/lib64/pkgconfig/polkit-qt5-1.pc
/usr/lib64/pkgconfig/polkit-qt5-agent-1.pc
/usr/lib64/pkgconfig/polkit-qt5-core-1.pc
/usr/lib64/pkgconfig/polkit-qt5-gui-1.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libpolkit-qt5-agent-1.so.1.114.0
/V3/usr/lib64/libpolkit-qt5-core-1.so.1.114.0
/V3/usr/lib64/libpolkit-qt5-gui-1.so.1.114.0
/usr/lib64/libpolkit-qt5-agent-1.so.1
/usr/lib64/libpolkit-qt5-agent-1.so.1.114.0
/usr/lib64/libpolkit-qt5-core-1.so.1
/usr/lib64/libpolkit-qt5-core-1.so.1.114.0
/usr/lib64/libpolkit-qt5-gui-1.so.1
/usr/lib64/libpolkit-qt5-gui-1.so.1.114.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/polkit-qt6/3e8971c6c5f16674958913a94a36b1ea7a00ac46
/usr/share/package-licenses/polkit-qt6/9950d3fdce1cff1f71212fb5abd31453c6ee2f8c
/usr/share/package-licenses/polkit-qt6/a4c60b3fefda228cd7439d3565df043192fef137
